title: NRF24LE1
description: Ferramentas para programação do módulo NRF24LE1.
show_downloads: true
theme: jekyll-theme-dinky
github:
  zip_url: https://github.com/italogfernandes/nrf24le1/releases/
  another_url: https://github.com/italogfernandes/nrf24le1/releases
